import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import Footer from "./Footer";
import "./globals.css";
import Header from "./Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Q2 UI/UX Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
