import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "./Footer";
import "./globals.css";
import Header from "./Header";
import { GlobalProvider } from "./GlobalProvider";
import { Metadata } from "next";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Q2 UI/UX Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <GlobalProvider>
          <Header />
          <main>
            {children}
            {/* <SanityLive/> */}
          </main>
          <Footer />
        </GlobalProvider>
        <Toaster />
      </body>
    </html>
  );
}
